@startuml
hide footbox
title Colocar una trampa en el terreno

actor Jugador as j

participant VistaBatalla as visBat
participant ControladorBatalla as contBat
participant SubVistaSeleccionTrampa as visTram
participant Accion as ac
participant Tablero as tab

activate j
j-> visBat:click en el boton trampa 

activate visBat
visBat-->contBat
activate contBat
contBat-> contBat:sePuedeColocarTrampa()

alt se puede colocar trampa

    contBat-> contBat: mostrarVistaSeleccionTrampa()
    
activate visTram
    contBat-> visTram: new SubVistaSeleccionTrampa()
    visTram--> contBat
    contBat-> visTram: agregarListenersVistaSeleccionTrampa(
    visTram--> j
    j-> visTram: click en la trampa que desea colocar
    visTram--> contBat
    contBat-> contBat:setTrampaAColocar()
    contBat-> visTram: dispose()
    deactivate visTram
    
    contBat-> ac: setTrampaAColocar(trampa)
    activate ac
    ac--> contBat
    deactivate ac
    
    contBat-> tab:setNumAccion(30)
    activate tab
    tab--> contBat
    deactivate tab
    
    contBat->visBat:deshabilitarBotones()
    contBat-> visBat:setMensaje("Selecciona una posicion\npara colocar la trampa.")
    visBat--> j: muestra mensaje

    ... Proceso para colocar la trampa (Diagrama Colocar trampa) ...

else no se puede colocar trampa

contBat->contBat:mostrarMensaje("No tienes puntos\nde trampa suficientes")
contBat--> j: muestra mensaje
end
@enduml