/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelos.Dado;
import Modelos.Jugador;
import Otros.BotonImagen;
import Otros.PanelImagen;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author mam28
 */
public class CompInfoJug extends PanelImagen {
    private final Jugador jugador;
    private final JLabel nombreJugador;
    private final JLabel tipoJugador;
    private final PanelImagen iconoJugador;
    private final ArrayList<Dado> dadosJugador;
    private final BotonImagen modificarPuzle;
    private final BotonImagen eliminar;
    
    public CompInfoJug(Jugador jugador, Font fuentePersonalizada){
        initComponents();
        
        this.setLayout(null);
        this.setBorder(null);
        this.setSize(350, 180);
        
        this.jugador = jugador;
        this.dadosJugador = jugador.getDados();
        
        this.nombreJugador = new JLabel(jugador.getNombreJugador());
        this.tipoJugador = new JLabel(jugador.getTipoJugador());
        this.iconoJugador = new PanelImagen("/Imagenes/Jefes/" +
                jugador.getJefeDeTerreno().getClave() + ".png");
        this.modificarPuzle = new BotonImagen("/Imagenes/Botones/boton.png");
        this.eliminar = new BotonImagen("/Imagenes/Botones/boton_cuadrado.png");
        
        this.add(nombreJugador);
        this.add(tipoJugador);
        this.add(iconoJugador);
        this.add(modificarPuzle);
        this.add(eliminar);
        
        this.iconoJugador.setSize(120, 120);
        this.iconoJugador.setLocation(0, 0);
        
        this.nombreJugador.setSize(200, 20);
        this.nombreJugador.setLocation(130, 0);
        this.nombreJugador.setForeground(Color.white);
        this.nombreJugador.setFont(new Font(fuentePersonalizada.getName(), 
                Font.TRUETYPE_FONT, 20));
        
        this.tipoJugador.setSize(200, 20);
        this.tipoJugador.setLocation(130,30);
        this.tipoJugador.setForeground(Color.white);
        this.tipoJugador.setFont(fuentePersonalizada);
        
        this.modificarPuzle.setText("Modificar puzle");
        this.modificarPuzle.setSize(200, 30);
        this.modificarPuzle.setLocation(130, 60);
        this.modificarPuzle.setForeground(Color.white);
        this.modificarPuzle.setImagenSobre("/Imagenes/Botones/boton_sobre.png");
        this.modificarPuzle.setImagenPresionado("/Imagenes/Botones/boton_presionado.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
