/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelos.Dado;
import Otros.BotonImagen;
import Otros.Constantes;
import Otros.PanelImagen;
import Otros.Reproductor;
import Otros.VistaPersonalizada;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author mam28
 */
public class SubVistaLanzamientoDados extends VistaPersonalizada {
    private final BotonImagen acumularPuntos;
    private final BotonImagen realizarAcciones;
    
    /**
     * Creates new form CompLanzamientoDados
     * @param caras Caras resultantes del lanzamiento de dados.
     * @param dados Dados que eligió el jugador.
     */
    public SubVistaLanzamientoDados(int[] caras, ArrayList<Dado> dados) {
        initComponents();
        
        this.acumularPuntos = new BotonImagen(Constantes.BTN_NORMAL);
        this.realizarAcciones = new BotonImagen(Constantes.BTN_NORMAL);
        
        this.add(acumularPuntos);
        this.add(realizarAcciones);
        
        this.acumularPuntos.setSize(200, 40);
        this.acumularPuntos.setLocation(180, 520);
        this.acumularPuntos.setText("Acumular puntos");
        this.acumularPuntos.setVisible(false);
        
        this.realizarAcciones.setSize(200, 40);
        this.realizarAcciones.setLocation(420, 520);
        this.realizarAcciones.setText("Realizar acciones");
        this.realizarAcciones.setVisible(false);
        
        final int ANCHO = 180;
        final int ALTO = ANCHO * 2;
        final int SEP = (800 - ANCHO * dados.size()) / (dados.size() + 1);
                
        for(int i = 0; i < dados.size(); i++){
            PanelImagen dado = new PanelImagen("/Imagenes/Dados/dado_" + dados.get(i).getNivel() 
                    + "_" + caras[i] + ".gif");
            this.add(dado, 0);
            dado.setSize(ANCHO, ALTO);
            dado.setLocation((SEP + ANCHO) * i + SEP, (this.getHeight() - ALTO) / 2);
        }
        
        this.setImagenFondo(Constantes.FONDO_LANZAMIENTO_DADOS);
        
        Timer timer = new Timer();      
        SubVistaLanzamientoDados vista = this;
        timer.schedule(new TimerTask(){
            int tic = 0;
            
            @Override
            public void run(){     
                switch (tic) {
                    case 5:
                        Reproductor.reproducirEfecto(Constantes.DADOS_SUBIENDO);
                        break;
                    case 25:
                    case 30:
                        Reproductor.reproducirEfecto(Constantes.CAE_DADO);
                        break;
                    case 34:
                        acumularPuntos.setVisible(true);
                        realizarAcciones.setVisible(true);
                        vista.repaint();
                        timer.cancel();
                        break;
                }
                tic++;
            }            
        }, 0, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public BotonImagen getAculumarPuntos() {
        return acumularPuntos;
    }

    public BotonImagen getRealizarAcciones() {
        return realizarAcciones;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
