/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelos.JefeDeTerreno;
import Otros.BotonImagen;
import Otros.Constantes;
import Otros.ContenedorScroll;
import Otros.PanelImagen;
import Otros.VistaPersonalizada;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JScrollPane;

/**
 *
 * @author mam28
 */
public class SubVistaSeleccionarJefe extends VistaPersonalizada {
    private final ArrayList<BotonImagen> panelesJefes;
    private final ArrayList<JefeDeTerreno> jefes;
    private final JScrollPane contenedor;
    private final PanelImagen contenedorJefes;
    private SubVistaInfoElemento visInfoEl;
        
    /**
     * Inicializa una nueva instancia de esta vista.
     */
    public SubVistaSeleccionarJefe() {
        initComponents();
        
        this.panelesJefes = new ArrayList<BotonImagen>();
        
        this.contenedorJefes = new PanelImagen();
        this.contenedorJefes.setLayout(null);
        
        this.contenedor = new ContenedorScroll();    
        this.add(this.contenedor);
        this.contenedor.setSize(598, 432);
        this.contenedor.setLocation(101, 84);
        this.contenedor.setViewportView(this.contenedorJefes);
        this.contenedor.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        this.contenedor.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        
        jefes = JefeDeTerreno.getJefes();
        
        final int N_COLUMNAS = 4;
        final int LADO = 100;
        final int SEP = (this.contenedor.getWidth() - N_COLUMNAS * LADO) / (N_COLUMNAS + 1);
        final int MARCO = 20;
        int columna = 0;
        int fila = -1;
        
        for (JefeDeTerreno jefe: jefes){
            fila = columna == 0 ? ++fila : fila;
            
            BotonImagen marcoJefe = new BotonImagen(Constantes.BTN_MARCO);
            this.contenedorJefes.add(marcoJefe);
            marcoJefe.setSize(LADO + MARCO, LADO + MARCO);
            marcoJefe.setLocation((SEP + LADO) * columna + SEP - MARCO / 2, (SEP + LADO) * fila + SEP - MARCO / 2);
            
            PanelImagen iconoJefe = new PanelImagen(Constantes.RUTA_JEFES
                    + jefe.getNomArchivoImagen() + Constantes.EXT1);
            this.contenedorJefes.add(iconoJefe);
            iconoJefe.setSize(LADO, LADO);
            iconoJefe.setLocation((SEP + LADO) * columna + SEP, (SEP + LADO) * fila + SEP);
            
            panelesJefes.add(marcoJefe);

            columna = columna == (N_COLUMNAS - 1)? 0: ++columna;
        }
        
        this.contenedorJefes.setPreferredSize(new Dimension(640, (LADO + SEP) * (fila + 1) + SEP));
        
        this.titulo.setFont(Constantes.FUENTE_18PX);
        
        this.setImagenFondo(Constantes.FONDO_SELECCION_3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setVisible(true);
        getContentPane().setLayout(null);

        titulo.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("<html><center>Selecciona un jefe de terreno. Puede mantener el mouse sobre alguno de los jefes para ver detalles del mismo.</center></html>");
        getContentPane().add(titulo);
        titulo.setBounds(50, 0, 700, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    public BotonImagen getPanelJefe(int i){
        return panelesJefes.get(i);
    }
    
    public int cantidadJefes(){
        return this.jefes.size();
    }
    
    public int idxJefe(BotonImagen panelJefe){
        return panelesJefes.indexOf(panelJefe);
    }
    
    public JefeDeTerreno getJefe(BotonImagen panelJefe){
        return jefes.get(this.idxJefe(panelJefe));
    }

    public SubVistaInfoElemento getVisInfoEl() {
        return visInfoEl;
    }

    public void setVisInfoEl(SubVistaInfoElemento visInfoEl) {
        this.visInfoEl = visInfoEl;
        this.add(visInfoEl, 0);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
