/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelos.JefeDeTerreno;
import Otros.BotonImagen;
import Otros.ContenedorScroll;
import Otros.PanelImagen;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JScrollPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author mam28
 */
public class SubVistaSeleccionarJefe extends JInternalFrame {
    private final ArrayList<BotonImagen> panelesJefes;
    private final ArrayList<JefeDeTerreno> jefes;
    private final JScrollPane contenedor;
    private final PanelImagen contenedorJefes;
        
    /**
     * Inicializa una nueva instancia de esta vista.
     * @param fuentePersonalizada Fuente que se utilizará en esta vista.
     */
    public SubVistaSeleccionarJefe(Font fuentePersonalizada){
        initComponents();
        
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        
        this.setOpaque(false);
        this.setBackground(new Color(0,0,0,0));
        
        this.panelesJefes = new ArrayList();
        
        this.contenedorJefes = new PanelImagen();
        this.contenedorJefes.setLayout(null);
        
        this.contenedor = new ContenedorScroll();    
        this.add(this.contenedor);
        this.contenedor.setSize(598, 335);
        this.contenedor.setLocation(101, 84);
        this.contenedor.setViewportView(this.contenedorJefes);
        this.contenedor.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        this.contenedor.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        
        jefes = JefeDeTerreno.getJefes();
        
        final int N_COLUMNAS = 4;
        final int LADO = 100;
        final int SEP = (this.contenedor.getWidth() - N_COLUMNAS * LADO) / (N_COLUMNAS + 1);
        final int MARCO = 20;
        int columna = 0;
        int fila = -1;
        
        for (JefeDeTerreno jefe: jefes){
            fila = columna == 0 ? ++fila : fila;
            
            BotonImagen marcoJefe = new BotonImagen("/Imagenes/vacio.png");
            this.contenedorJefes.add(marcoJefe);
            marcoJefe.setSize(LADO + MARCO, LADO + MARCO);
            marcoJefe.setImagenSobre("/Imagenes/Otros/marco_seleccion.png");
            marcoJefe.setLocation((SEP + LADO) * columna + SEP - MARCO / 2, (SEP + LADO) * fila + SEP - MARCO / 2);
            
            PanelImagen iconoJefe = new PanelImagen("/Imagenes/Jefes/"
                    + jefe.getNomArchivoImagen() + ".png");
            this.contenedorJefes.add(iconoJefe);
            iconoJefe.setSize(LADO, LADO);
            iconoJefe.setLocation((SEP + LADO) * columna + SEP, (SEP + LADO) * fila + SEP);
            
            panelesJefes.add(marcoJefe);

            columna = columna == (N_COLUMNAS - 1)? 0: ++columna;
        }
        
        this.contenedorJefes.setPreferredSize(new Dimension(640, (LADO + SEP) * (fila + 1) + SEP));
        
        PanelImagen panelFondo = new PanelImagen("/Imagenes/Fondos/fondo_seleccion_2.png");
        this.add(panelFondo);
        panelFondo.setSize(this.getSize());
        
        this.nombre.setFont(new Font(fuentePersonalizada.getName(), Font.TRUETYPE_FONT, 36));
        this.habilidad.setFont(new Font(fuentePersonalizada.getName(), Font.TRUETYPE_FONT, 24));
        
        this.setNombre("");
        this.setHabilidad("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        habilidad = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setVisible(true);
        getContentPane().setLayout(null);

        habilidad.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        habilidad.setForeground(new java.awt.Color(204, 0, 0));
        habilidad.setText("Habilidad");
        getContentPane().add(habilidad);
        habilidad.setBounds(110, 490, 610, 29);

        nombre.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("Nombre");
        getContentPane().add(nombre);
        nombre.setBounds(110, 445, 610, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void mostrarInformacionJefe(int indiceJefe){
        this.nombre.setText(this.jefes.get(indiceJefe).getNombre());
        this.habilidad.setText(this.jefes.get(indiceJefe).getDescripcion());
    }
    
    public void borrarCampos(){
        this.nombre.setText("");
        this.habilidad.setText("");
    }
    
    public ArrayList<BotonImagen> getPanelesJefes() {
        return panelesJefes;
    }

    public ArrayList<JefeDeTerreno> getJefes() {
        return jefes;
    }
    
    public void setNombre(String nombre){
        this.nombre.setText(nombre);
    }
    
    public void setHabilidad(String habilidad){
        this.habilidad.setText(habilidad);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel habilidad;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
