/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Otros.BotonImagen;
import Otros.Constantes;
import Otros.PanelImagen;
import Otros.VistaPersonalizada;
import java.awt.Font;
import java.util.ArrayList;

/**
 *
 * @author mam28
 */
public class SubVistaSeleccionDespliegue extends VistaPersonalizada {
    ArrayList<BotonImagen> botonesDespliegue;
    /**
     * Creates new form CompSelDesp
     */
    public SubVistaSeleccionDespliegue() {
        initComponents();
        
        this.botonesDespliegue = new ArrayList();
        
        String[] nomDespliegues = {"cruz", "escalera", "t", "s", "4", "r"};
        int filas = 2;
        int columnas = 3;
        int lado = 130;
        int numDespliegues = nomDespliegues.length;
        int separacionHorizontal = (640 - lado * columnas) / (columnas + 1);
        int separacionVertical = (480 - lado * filas) / (filas + 1);
        int marco = 20;
        
        for(int i = 0; i < numDespliegues; i++){
            BotonImagen botonDespliegue = new BotonImagen(Constantes.BTN_MARCO);
            this.add(botonDespliegue);
            botonDespliegue.setSize(lado + marco, lado + marco);
            botonDespliegue.setName(String.valueOf(i));
            botonesDespliegue.add(botonDespliegue);
            
            PanelImagen fondoDespliegue = new PanelImagen(
                    Constantes.IMAGEN_DESPLIEGUE + nomDespliegues[i] + Constantes.EXT2);
            this.add(fondoDespliegue);
            fondoDespliegue.setSize(lado, lado);
            
            int x = 90 + (separacionHorizontal + lado) * (i % columnas) + separacionHorizontal;
            int y = 60 + (separacionVertical + lado) * (i / columnas) + separacionVertical;
            
            fondoDespliegue.setLocation(x, y);
            botonDespliegue.setLocation(x - marco / 2, y - marco / 2);
        }
        
        this.titulo.setFont(Constantes.FUENTE_24PX);
        
        this.setImagenFondo(Constantes.FONDO_SELECCION_3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        titulo.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Selecciona un despliegue de dado");
        getContentPane().add(titulo);
        titulo.setBounds(0, 10, 790, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<BotonImagen> getBotonesDespliegue() {
        return botonesDespliegue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
