/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Otros.BotonImagen;
import Otros.PanelImagen;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author mam28
 */
public class SubVistaSeleccionDespliegue extends javax.swing.JInternalFrame {
    ArrayList<BotonImagen> botonesDespliegue;
    /**
     * Creates new form CompSelDesp
     */
    public SubVistaSeleccionDespliegue() {
        initComponents();
        
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        
        this.setOpaque(false);
        this.setBackground(new Color(0,0,0,0));
        
        this.botonesDespliegue = new ArrayList();
        
        String[] nomDespliegues = {"cruz", "escalera", "t", "s", "4", "r"};
        int filas = 2;
        int columnas = 3;
        int lado = 130;
        int numDespliegues = nomDespliegues.length;
        int separacionHorizontal = (640 - lado * columnas) / (columnas + 1);
        int separacionVertical = (480 - lado * filas) / (filas + 1);
        int aumentoMarco = 20;
        
        for(int i = 0; i < numDespliegues; i++){
            BotonImagen botonDespliegue = new BotonImagen("/Imagenes/vacio.png");
            this.add(botonDespliegue);
            botonDespliegue.setImagenSobre("/Imagenes/Otros/marco_seleccion.png");
            botonDespliegue.setSize(lado + aumentoMarco, lado + aumentoMarco);
            botonDespliegue.setName(String.valueOf(i));
            botonesDespliegue.add(botonDespliegue);
            
            PanelImagen fondoDespliegue = new PanelImagen(
                    "/Imagenes/Otros/despliegue_" + nomDespliegues[i] + ".gif");
            this.add(fondoDespliegue);
            fondoDespliegue.setSize(lado, lado);
            
            int x = 90 + (separacionHorizontal + lado) * (i % columnas) + separacionHorizontal;
            int y = 60 + (separacionVertical + lado) * (i / columnas) + separacionVertical;
            
            fondoDespliegue.setLocation(x, y);
            botonDespliegue.setLocation(x - aumentoMarco / 2, y - aumentoMarco / 2);
        }
        
        PanelImagen panelFondo = new PanelImagen("/Imagenes/Fondos/fondo_seleccion_3.png");
        this.add(panelFondo);
        panelFondo.setSize(this.getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<BotonImagen> getBotonesDespliegue() {
        return botonesDespliegue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
