/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelos.Criatura;
import Otros.BotonImagen;
import Otros.Constantes;
import Otros.PanelImagen;
import Otros.VistaPersonalizada;
import java.util.ArrayList;

/**
 *
 * @author mam28
 */
public class SubVistaCriaturaRevivir extends VistaPersonalizada {
    private final ArrayList<BotonImagen> panelesCriaturas;
    private final ArrayList<Criatura> criaturas;
    
    /**
     * Creates new form SubVistaSeleccionCriatura
     * @param criaturas
     */
    public SubVistaCriaturaRevivir(ArrayList<Criatura> criaturas) {
        initComponents();
        
        this.criaturas = criaturas;
        this.panelesCriaturas = new ArrayList<BotonImagen>();
        
        final int N_COLUMNAS = criaturas.size();
        final int LADO = 100;
        final int SEP = (640 - N_COLUMNAS * LADO) / (N_COLUMNAS + 1);
        final int MARCO = 20;
        int columna = 0;
        int fila = -1;
        
        for (Criatura criatura: criaturas){
            fila = columna == 0 ? ++fila : fila;
            
            BotonImagen marcoCriatura = new BotonImagen(Constantes.BTN_MARCO);
            this.add(marcoCriatura);
            marcoCriatura.setSize(LADO + MARCO, LADO + MARCO);
            marcoCriatura.setLocation((SEP + LADO) * columna + SEP - MARCO / 2 + 80, (this.getHeight() - LADO - MARCO) / 2);
            
            PanelImagen iconoCriatura = new PanelImagen(Constantes.RUTA_CRIATURAS
                    + criatura.getNomArchivoImagen() + Constantes.EXT1);
            this.add(iconoCriatura);
            iconoCriatura.setSize(LADO, LADO);
            iconoCriatura.setLocation((SEP + LADO) * columna + SEP + 80, (this.getHeight() - LADO) / 2);
            
            panelesCriaturas.add(marcoCriatura);

            columna = columna == (N_COLUMNAS - 1)? 0: ++columna;
        }
        
        this.titulo.setFont(Constantes.FUENTE_24PX);
        
        this.setImagenFondo(Constantes.FONDO_SELECCION_3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        titulo.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Elige la criatura que deseas revivir.");
        getContentPane().add(titulo);
        titulo.setBounds(0, 10, 790, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public BotonImagen getPanelCriatura(int i) {
        return panelesCriaturas.get(i);
    } 
    
    public Criatura getCriatura(BotonImagen panelCriatura){
        return this.criaturas.get(this.panelesCriaturas.indexOf(panelCriatura));
    }
    
    public int getCantidadCriaturas(){
        return this.panelesCriaturas.size();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
