/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Otros.Constantes;
import Otros.PanelImagen;
import Otros.Reproductor;
import Otros.VistaPersonalizada;

/**
 *
 * @author mam28
 */
public class SubVistaCambioTurno extends VistaPersonalizada {

    /**
     * Creates new form SubVistaCambioTurno
     * @param turno Turno actual.
     */
    public SubVistaCambioTurno(int turno) {
        initComponents();
        
        PanelImagen panelAnimacion = new PanelImagen("/Imagenes/Otros/turno_j" + (turno + 1) + ".gif");
        this.add(panelAnimacion);
        panelAnimacion.setSize(800, 200);
        panelAnimacion.setLocation(0, 200);
        
        this.setImagenFondo("/Imagenes/vacio_oscuro.png");
        
        Reproductor.reproducirEfecto(Constantes.CAMBIO_TURNO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
