/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelos.Dado;
import Modelos.Jugador;
import Otros.BotonImagen;
import Otros.Constantes;
import Otros.PanelImagen;
import Otros.Reproductor;
import Otros.VistaPersonalizada;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JLabel;

/**
 *
 * @author mam28
 */
public final class VistaTorneoFinalizado extends VistaPersonalizada {
    private final BotonImagen aceptar;

    /**
     * Creates new form VistaTorneoFinalizado
     * @param ganador Jugador que ganó el torneo.
     * @param dadosGanados Dados que ganó el jugador.
     */
    public VistaTorneoFinalizado(Jugador ganador, ArrayList<Dado> dadosGanados) {
        initComponents();
        
        PanelImagen iconoJugador = new PanelImagen(Constantes.RUTA_JEFES +
                ganador.getJefeDeTerreno().getNomArchivoImagen() + Constantes.EXT1);
        this.add(iconoJugador);
        iconoJugador.setSize(100, 100);
        iconoJugador.setLocation(350, 100);
        
        JLabel L1 = new JLabel("El ganador es:");
        this.add(L1);
        L1.setSize(800, 30);
        L1.setLocation(0, 50);
        L1.setHorizontalAlignment(JLabel.CENTER);
        L1.setFont(Constantes.FUENTE_36PX);
        L1.setForeground(Color.white);
        
        JLabel nombre = new JLabel(ganador.getNombreJugador());
        this.add(nombre);
        nombre.setSize(800, 20);
        nombre.setLocation(0, 210);
        nombre.setHorizontalAlignment(JLabel.CENTER);
        nombre.setFont(Constantes.FUENTE_24PX);
        nombre.setForeground(Color.white);
        
        JLabel L2 = new JLabel("Y ha ganado los siguientes dados:");
        this.add(L2);
        L2.setSize(800, 30);
        L2.setLocation(0, 250);
        L2.setHorizontalAlignment(JLabel.CENTER);
        L2.setFont(Constantes.FUENTE_36PX);
        L2.setForeground(Color.white);
        
        this.aceptar = new BotonImagen(Constantes.BTN_NORMAL);
        this.add(aceptar);
        this.aceptar.setText("Aceptar");
        this.aceptar.setSize(160, 40);
        this.aceptar.setLocation(320, 540);
        this.aceptar.setVisible(false);
        
        this.setImagenFondo(Constantes.FONDO_SELECCION_1);
        
        this.mostrarDadosGanados(dadosGanados);
        
        Reproductor.reproducir(Constantes.M_TORNEO_FINALIZADO);
    }

    /**
     * Creates new form VistaTorneoFinalizado
     * @param ganador Jugador que ganó el torneo.
     */
    public VistaTorneoFinalizado(Jugador ganador) {
        initComponents();
        
        PanelImagen iconoJugador = new PanelImagen(Constantes.RUTA_JEFES +
                ganador.getJefeDeTerreno().getNomArchivoImagen() + Constantes.EXT1);
        this.add(iconoJugador);
        iconoJugador.setSize(100, 100);
        iconoJugador.setLocation(350, 250);
        
        JLabel L1 = new JLabel("El ganador es:");
        this.add(L1);
        L1.setSize(800, 30);
        L1.setLocation(0, 200);
        L1.setHorizontalAlignment(JLabel.CENTER);
        L1.setFont(Constantes.FUENTE_36PX);
        L1.setForeground(Color.white);
        
        JLabel nombre = new JLabel(ganador.getNombreJugador());
        this.add(nombre);
        nombre.setSize(800, 20);
        nombre.setLocation(0, 360);
        nombre.setHorizontalAlignment(JLabel.CENTER);
        nombre.setFont(Constantes.FUENTE_24PX);
        nombre.setForeground(Color.white);
        
        this.aceptar = new BotonImagen(Constantes.BTN_NORMAL);
        this.add(aceptar);
        this.aceptar.setText("Aceptar");
        this.aceptar.setSize(160, 40);
        this.aceptar.setLocation(320, 540);
        this.aceptar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarDadosGanados(ArrayList<Dado> dadosGanados) {
        final int LADO = 100;
        final int CANTIDAD = dadosGanados.size();
        final int SEP = (this.getWidth() - LADO * CANTIDAD) / (CANTIDAD + 1);
        
        Timer timerAnimacion = new Timer();
        timerAnimacion.schedule(new TimerTask(){
            int tic = 0;
            @Override
            public void run(){
                Dado dadoAct = dadosGanados.get(tic);

                PanelImagen panelDado = new PanelImagen(Constantes.RUTA_CRIATURAS +
                        dadoAct.getCriatura().getNomArchivoImagen() + Constantes.EXT1);
                add(panelDado, 0);
                panelDado.setSize(LADO, LADO);
                panelDado.setLocation((SEP + LADO) * tic + SEP, 300);

                Reproductor.reproducirEfecto(Constantes.RUTA_EFECTOS + "step" + 
                        (tic + 1) + Constantes.EXT_E);
                
                tic++;
                
                if(tic == CANTIDAD){
                    aceptar.setVisible(true);
                    this.cancel();
                    timerAnimacion.cancel();
                }
            }
        }, 2000, 1000);
    }

    public BotonImagen getAceptar() {
        return aceptar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
