/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Otros.BotonCheckImagen;
import Otros.BotonImagen;
import Otros.Constantes;
import Otros.PanelImagen;
import Otros.VistaPersonalizada;
import java.util.ArrayList;

/**
 *
 * @author mam28
 */
public class VistaNuevaPartida extends VistaPersonalizada {
    private SubVistaSeleccionEquipos visSelEq;
    private SubVistaCambiarJugador visCamJug;
    private SubVistaCambiarNivel visCamNiv;
    private final ArrayList<SubVistaResumenJugador> vistasResJug;
    private final BotonImagen agregar;
    private final BotonCheckImagen enEquipos;
    private final BotonImagen volver;
    private final BotonImagen registrar;
    private final BotonImagen comenzar;
    private final int[][] posVisResJug = 
    {{50, 90}, {410, 90}, {50, 275}, {410, 275}};
    
    /**
     * Creates new form VistaNuevaPartida
     */
    public VistaNuevaPartida() {
        initComponents();
        
        this.vistasResJug = new ArrayList<SubVistaResumenJugador>();
        
        this.agregar = new BotonImagen(Constantes.BTN_REDONDO);
        this.add(agregar);        
        agregar.setSize(100, 100);
        agregar.setLocation(40, 475);
        agregar.setLayout(null);
        
        PanelImagen iconoAgregar = new PanelImagen("/Imagenes/Otros/cruz.png");
        agregar.add(iconoAgregar);
        iconoAgregar.setSize(agregar.getWidth() / 2, agregar.getHeight() / 2);
        iconoAgregar.setLocation((agregar.getWidth() - iconoAgregar.getWidth()) / 2, 
                (agregar.getHeight() - iconoAgregar.getHeight()) / 2);
        
        this.enEquipos = new BotonCheckImagen(Constantes.BTN_REDONDO);
        this.add(enEquipos);
        
        enEquipos.setSize(100, 100);
        enEquipos.setLocation(160, 475);
        enEquipos.setLayout(null);
        
        PanelImagen iconoEnEquipos = new PanelImagen("/Imagenes/Otros/equipo.png");
        enEquipos.add(iconoEnEquipos);
        iconoEnEquipos.setSize(enEquipos.getWidth() / 2, enEquipos.getHeight() / 2);
        iconoEnEquipos.setLocation((enEquipos.getWidth() - iconoEnEquipos.getWidth()) / 2, 
                (enEquipos.getHeight() - iconoEnEquipos.getHeight()) / 2);
                
        this.volver = new BotonImagen(Constantes.BTN_ATRAS);
        this.add(this.volver);
        this.volver.setLocation(35, 35);
        this.volver.setSize(40, 40);   
                
        this.registrar = new BotonImagen(Constantes.BTN_NORMAL);
        this.add(this.registrar);
        this.registrar.setLocation(85, 35);
        this.registrar.setSize(160, 40);     
        this.registrar.setText("Registrar jugador");
                
        this.comenzar = new BotonImagen(Constantes.BTN_NORMAL);
        this.add(this.comenzar);
        this.comenzar.setLocation(255, 35);
        this.comenzar.setSize(160, 40);     
        this.comenzar.setText("Comenzar partida");
        
        this.setImagenFondo(Constantes.FONDO_SELECCION_1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int[][] getPosVisResJug() {
        return posVisResJug;
    }
    
    public BotonImagen getAgregar() {
        return agregar;
    }

    public BotonCheckImagen getEnEquipos() {
        return enEquipos;
    }

    public BotonImagen getVolver() {
        return volver;
    }

    public BotonImagen getRegistrar() {
        return registrar;
    }

    public BotonImagen getComenzar() {
        return comenzar;
    }
    
    public void agregarVisResJug(SubVistaResumenJugador visResJug){
        this.vistasResJug.add(visResJug);
    }
    
    public void eliminarVisResJug(int i){
        this.vistasResJug.get(i).setVisible(false);
        this.vistasResJug.remove(i);
    }
    
    public SubVistaResumenJugador getVisResJug(int i){
        return this.vistasResJug.get(i);
    }

    public SubVistaSeleccionEquipos getVisSelEq() {
        return visSelEq;
    }

    public SubVistaCambiarJugador getVisCamJug() {
        return visCamJug;
    }

    public SubVistaCambiarNivel getVisCamNiv() {
        return visCamNiv;
    }

    public void setVisSelEq(SubVistaSeleccionEquipos visSelEq) {
        this.visSelEq = visSelEq;
    }

    public void setVisCamJug(SubVistaCambiarJugador visCamJug) {
        this.visCamJug = visCamJug;
    }

    public void setVisCamNiv(SubVistaCambiarNivel visCamNiv) {
        this.visCamNiv = visCamNiv;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}