/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelos.Jugador;
import Otros.BotonImagen;
import Otros.Constantes;
import Otros.PanelImagen;
import Otros.Reproductor;
import Otros.VistaPersonalizada;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author mam28
 */
public class VistaResumenTorneo extends VistaPersonalizada {
    private final BotonImagen terminarTorneo;
    private final BotonImagen siguientePartida;

    /**
     * Creates new form VistaResumenTorneo
     * @param clasificacion Clasificación de los jugadores en el torneo.
     * @param partJugadas Cantidad de partidas jugadas en el torneo.
     */
    public VistaResumenTorneo(ArrayList<Jugador> clasificacion, int partJugadas) {
        initComponents();
        
        this.terminarTorneo = new BotonImagen(Constantes.BTN_NORMAL);
        this.add(this.terminarTorneo);
        this.terminarTorneo.setText("Finalizar torneo");
        this.terminarTorneo.setSize(160, 40);
        this.terminarTorneo.setLocation(460, 550);
        
        this.siguientePartida = new BotonImagen(Constantes.BTN_NORMAL);
        this.add(this.siguientePartida);
        this.siguientePartida.setText("Siguiente batalla");
        this.siguientePartida.setSize(160, 40);
        this.siguientePartida.setLocation(630, 550);
        
        if(partJugadas == 3){
            this.siguientePartida.setEnabled(false);
        }
        
        
        final int ANCHO = 400;
        final int ALTO = 50;
        final int LADO_ICONO = ALTO * 80 / 100;
        final int UBICACION_ICONO = (ALTO - LADO_ICONO) / 2;
        final int CANTIDAD = clasificacion.size();
        final int SEP = (this.getHeight() - 200 - ALTO * CANTIDAD) / (CANTIDAD + 1);
        
        for(int i = 0; i < clasificacion.size(); i++){
            PanelImagen panelClas = new PanelImagen(Constantes.BARRA_CLASIFICACION);
            this.add(panelClas);
            panelClas.setSize(ANCHO, ALTO);
            panelClas.setLocation((this.getWidth() - ANCHO) / 2, (SEP + ALTO) * i + SEP + 100);
            
            Jugador jugAct = clasificacion.get(i);
            PanelImagen iconoJugador = new PanelImagen(Constantes.RUTA_JEFES +
                    jugAct.getJefeDeTerreno().getNomArchivoImagen() + Constantes.EXT1);
            panelClas.add(iconoJugador);
            iconoJugador.setSize(LADO_ICONO, LADO_ICONO);
            iconoJugador.setLocation(UBICACION_ICONO, UBICACION_ICONO);
            
            JLabel nombre = new JLabel(jugAct.getNombreJugador());
            panelClas.add(nombre);
            nombre.setFont(Constantes.FUENTE_18PX);
            nombre.setForeground(Color.white);
            nombre.setSize(300, 25);
            nombre.setLocation(ALTO + 20, UBICACION_ICONO);
            
            JLabel puntaje = new JLabel("Puntaje actual: " + jugAct.getPuntaje());
            panelClas.add(puntaje);
            puntaje.setFont(Constantes.FUENTE_14PX);
            puntaje.setForeground(Color.white);
            puntaje.setSize(300, 25);
            puntaje.setLocation(ALTO + 15, UBICACION_ICONO + 20);
        }
        
        this.setImagenFondo(Constantes.FONDO_MENU_PRINCIPAL);
        
        Reproductor.reproducir(Constantes.M_NUEVO_TORNEO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public BotonImagen getTerminarTorneo() {
        return terminarTorneo;
    }

    public BotonImagen getSiguientePartida() {
        return siguientePartida;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
