/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import Otros.BotonImagen;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author mam28
 */
public class VistaRegistro extends javax.swing.JInternalFrame {
    private VistaPrincipal vistaPrincipal;
    private BotonImagen registrarse;
    
    /**
     * Creates new form VistaRegistro
     */
    public VistaRegistro() {
        initComponents();
    }
    
    /**
     * Inicializar VistaLogin
     * @param vistaPrincipal Vista principal que contiene a este JInternalFrame
     */
    public VistaRegistro(VistaPrincipal vistaPrincipal){
        this.vistaPrincipal = vistaPrincipal;
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        initComponents();
        
        this.registrarse = new BotonImagen("/Imagenes/boton.png");
        this.add(this.registrarse);
        this.registrarse.setImagenSobre("/Imagenes/boton_mouse_sobre.png");
        this.registrarse.setImagenPresionado("/Imagenes/boton_presionado.png");
        this.registrarse.setLocation(290, 390);
        this.registrarse.setSize(230, 40);
        this.registrarse.setText("Registrarse");
        this.registrarse.setFont(vistaPrincipal.getFont());
        this.registrarse.setForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mensaje = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        L3 = new javax.swing.JLabel();
        Pass = new javax.swing.JPasswordField();
        RepitePass = new javax.swing.JPasswordField();
        volver = new javax.swing.JButton();

        setBorder(null);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(810, 608));
        setMinimumSize(new java.awt.Dimension(810, 608));
        setPreferredSize(new java.awt.Dimension(810, 608));
        getContentPane().setLayout(null);

        Mensaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mensaje.setText("Mensaje");
        getContentPane().add(Mensaje);
        Mensaje.setBounds(290, 240, 230, 14);
        Mensaje.setFont(vistaPrincipal.getFont());

        L1.setText("Usuario:");
        getContentPane().add(L1);
        L1.setBounds(290, 270, 90, 20);

        L2.setText("Pass:");
        getContentPane().add(L2);
        L2.setBounds(290, 310, 90, 20);
        getContentPane().add(Usuario);
        Usuario.setBounds(380, 270, 140, 20);

        L3.setText("Repetir pass:");
        getContentPane().add(L3);
        L3.setBounds(290, 350, 90, 20);
        getContentPane().add(Pass);
        Pass.setBounds(380, 310, 140, 20);
        getContentPane().add(RepitePass);
        RepitePass.setBounds(380, 350, 140, 20);

        volver.setLabel("<");
        getContentPane().add(volver);
        volver.setBounds(20, 10, 50, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getVolver() {
        return volver;
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel Mensaje;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JPasswordField RepitePass;
    private javax.swing.JTextField Usuario;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
