/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import Otros.BotonImagen;
import Otros.PanelImagen;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author mam28
 */
public class VistaMenuPrincipal extends javax.swing.JInternalFrame {
    private VistaPrincipal vistaPrincipal;
    
    /**
     * Creates new form VistaMenuPrincipal
     */
    public VistaMenuPrincipal() {
        initComponents();
    }
    
    public VistaMenuPrincipal(VistaPrincipal vistaPrincipal){
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.vistaPrincipal = vistaPrincipal;
        initComponents();
        
        int cantidadCompoenentes = 3;
        int separacion = (this.getSize().width - 200 * cantidadCompoenentes) 
                / (cantidadCompoenentes + 1);
        String[] imagenBoton = {"/Imagenes/partida.png", "/Imagenes/torneo.png", "/Imagenes/torneo.png"};
        String[] imagenBotonSobre = {"/Imagenes/partida_sobre.png", 
            "/Imagenes/torneo_sobre.png", "/Imagenes/torneo_sobre.png"};
        String[] imagenBotonPresionado = {"/Imagenes/partida_presionado.png", 
            "/Imagenes/torneo_presionado.png", "/Imagenes/torneo_presionado.png"};
        String[] mensajeBoton = {"Nueva partida", "Nuevo torneo", "Opcion 3"};
        
        for (int i = 0; i < cantidadCompoenentes; i ++){
            final int index = i;
            int posicionX = 200 * i + separacion * (i + 1);
            
            BotonImagen boton = new BotonImagen(imagenBoton[i]);
            boton.setSize(200, 320);
            boton.setLocation(posicionX, 140);
            boton.setImagenSobre(imagenBotonSobre[i]);
            boton.setImagenPresionado(imagenBotonPresionado[i]);
            boton.addMouseListener(new MouseAdapter(){
                @Override
                public void mouseEntered(MouseEvent e){
                    mensaje.setText(mensajeBoton[index]);
                }
                
                @Override
                public void mouseExited(MouseEvent e){
                    mensaje.setText("");
                }
            });
            this.add(boton);
            
            PanelImagen panel = new PanelImagen("/Imagenes/cajon_menu.png");
            panel.setSize(boton.getSize());
            panel.setLocation(posicionX, 140);
            this.add(panel);
        }
        
        PanelImagen panelFondo = new PanelImagen("/Imagenes/fondo_menu_principal.png");
        panelFondo.setSize(this.getSize());
        this.add(panelFondo);
        
        mensaje.setFont(new Font(vistaPrincipal.getFont().getName(), 
                Font.TRUETYPE_FONT, 36));
        
        mensaje.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensaje = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        mensaje.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        mensaje.setForeground(new java.awt.Color(255, 255, 255));
        mensaje.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mensaje.setText("Mensaje");
        getContentPane().add(mensaje);
        mensaje.setBounds(410, 540, 360, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mensaje;
    // End of variables declaration//GEN-END:variables
}
