/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Font;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author mam28
 */
public class VistaBatalla extends javax.swing.JInternalFrame {
    private CompTablero tablero;
    
    /**
     * Creates new form VistaBatalla
     * @param fuentePersonalizada Fuente que se utilizará en esta vista.
     */
    public VistaBatalla(Font fuentePersonalizada) {
        initComponents();
        
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        
        int[][] posiciones = {{5, 5}, {655, 5}, {5, 405}, {655, 405}};
        for(int i = 0; i < 4; i++){
            CompJugador cp = new CompJugador(fuentePersonalizada);
            this.add(cp);
            cp.setLocation(posiciones[i][0], posiciones[i][1]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensaje = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        mensaje.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        mensaje.setForeground(new java.awt.Color(255, 255, 255));
        mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensaje.setText("Mensaje");
        getContentPane().add(mensaje);
        mensaje.setBounds(180, 10, 450, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public CompTablero getTablero() {
        return tablero;
    }

    public void setTablero(CompTablero tablero) {
        this.tablero = tablero;
    }
    
    public void setMensaje(String mensaje){
        this.mensaje.setText(mensaje);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mensaje;
    // End of variables declaration//GEN-END:variables
}
