/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Otros.BotonImagen;
import Otros.PanelImagen;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author mam28
 */
public class VistaBatalla extends javax.swing.JInternalFrame {
    private CompTablero tablero;
    private BotonImagen ataque;
    private BotonImagen invocacion;
    private BotonImagen magia;
    private BotonImagen movimiento;
    private BotonImagen trampa;
    private CompJugador[] vistasJugador;
    private CompSelDesp visSelDesp;
    
    /**
     * Creates new form VistaBatalla
     * @param fuentePersonalizada Fuente que se utilizará en esta vista.
     */
    public VistaBatalla(Font fuentePersonalizada) {
        initComponents();
        
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        
        this.visSelDesp = new CompSelDesp();
        this.vistasJugador = new CompJugador[4];
        
        int[][] posiciones = {{5, 5}, {655, 5}, {5, 405}, {655, 405}};
        for(int i = 0; i < 4; i++){
            CompJugador resumenJugador = new CompJugador(fuentePersonalizada);
            
            if(i == 0){
                resumenJugador.setImagen("/Imagenes/Fondos/fondo_jugador.png");
            }else{
                resumenJugador.setImagen("/Imagenes/Fondos/fondo_jugador_inactivo.png");
            }
            
            this.add(resumenJugador);
            resumenJugador.setLocation(posiciones[i][0], posiciones[i][1]);
            vistasJugador[i] = resumenJugador;
        }
        
        this.ataque = new BotonImagen("/Imagenes/Botones/ataque.png");
        this.invocacion = new BotonImagen("/Imagenes/Botones/invocacion.png");
        this.magia = new BotonImagen("/Imagenes/Botones/magia.png");
        this.movimiento = new BotonImagen("/Imagenes/Botones/movimiento.png");
        this.trampa = new BotonImagen("/Imagenes/Botones/trampa.png");
        
        this.add(ataque);
        this.add(invocacion);
        this.add(magia);
        this.add(movimiento);
        this.add(trampa);
        
        this.ataque.setSize(30, 30);
        this.invocacion.setSize(30, 30);
        this.magia.setSize(30, 30);
        this.movimiento.setSize(30, 30);
        this.trampa.setSize(30, 30);
        
        this.ataque.setLocation(170, 560);
        this.invocacion.setLocation(210, 560);
        this.magia.setLocation(250, 560);
        this.movimiento.setLocation(290, 560);
        this.trampa.setLocation(330, 560);
        
        this.ataque.setImagenSobre("/Imagenes/Botones/ataque_sobre.png");
        this.invocacion.setImagenSobre("/Imagenes/Botones/invocacion_sobre.png");
        this.magia.setImagenSobre("/Imagenes/Botones/magia_sobre.png");
        this.movimiento.setImagenSobre("/Imagenes/Botones/movimiento_sobre.png");
        this.trampa.setImagenSobre("/Imagenes/Botones/trampa_sobre.png");
        
        this.ataque.setImagenPresionado("/Imagenes/Botones/ataque_presionado.png");
        this.invocacion.setImagenPresionado("/Imagenes/Botones/invocacion_presionado.png");
        this.magia.setImagenPresionado("/Imagenes/Botones/magia_presionado.png");
        this.movimiento.setImagenPresionado("/Imagenes/Botones/movimiento_presionado.png");
        this.trampa.setImagenPresionado("/Imagenes/Botones/trampa_presionado.png");
        
        mensaje.setText("");
        mensaje.setFont(new Font(fuentePersonalizada.getName(), Font.TRUETYPE_FONT, 16));
        
        PanelImagen panelFondo = new PanelImagen("/Imagenes/Fondos/fondo_batalla.png");
        this.add(panelFondo);
        panelFondo.setSize(this.getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensaje = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        mensaje.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        mensaje.setForeground(new java.awt.Color(255, 255, 255));
        mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensaje.setText("Mensaje");
        getContentPane().add(mensaje);
        mensaje.setBounds(180, 10, 450, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public CompTablero getTablero() {
        return tablero;
    }

    public BotonImagen getAtaque() {
        return ataque;
    }

    public BotonImagen getInvocacion() {
        return invocacion;
    }

    public BotonImagen getMagia() {
        return magia;
    }

    public BotonImagen getMovimiento() {
        return movimiento;
    }

    public BotonImagen getTrampa() {
        return trampa;
    }

    public CompJugador[] getVistasJugador() {
        return vistasJugador;
    }

    public JLabel getMensaje() {
        return mensaje;
    }

    public CompSelDesp getVisSelDesp() {
        return visSelDesp;
    }

    public void setTablero(CompTablero tablero) {
        this.tablero = tablero;
    }
    
    public void setMensaje(String mensaje){
        this.mensaje.setText(mensaje);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mensaje;
    // End of variables declaration//GEN-END:variables
}
