--Jugador
INSERT INTO JUGADOR (NOMBREJUGADOR, ESHUMANO, ID_JEFEDETERRENO)
	VALUES('Link', false, 1);

--Dados
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(1, 1, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(1, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(1, 3, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(1, 4, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(1, 10, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(1, 5, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(1, 4, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(1, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(1, 12, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(1, 16, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(1, 18, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(1, 13, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(1, 22, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(1, 24, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(1, 28, true);

--Jugador
INSERT INTO JUGADOR (NOMBREJUGADOR, ESHUMANO, ID_JEFEDETERRENO)
	VALUES('Zelda', false, 2);

--Dados
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(2, 8, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(2, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(2, 3, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(2, 4, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(2, 10, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(2, 5, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(2, 4, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(2, 8, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(2, 12, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(2, 14, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(2, 18, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(2, 13, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(2, 21, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(2, 24, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(2, 26, true);

--Jugador
INSERT INTO JUGADOR (NOMBREJUGADOR, ESHUMANO, ID_JEFEDETERRENO)
	VALUES('Ganondorf', false, 3);

--Dados
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(3, 6, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(3, 8, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(3, 3, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(3, 9, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(3, 10, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(3, 9, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(3, 4, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(3, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(3, 11, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(3, 13, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(3, 15, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(3, 13, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(3, 23, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(3, 25, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(3, 27, true);

--Jugador
INSERT INTO JUGADOR (NOMBREJUGADOR, ESHUMANO, ID_JEFEDETERRENO)
	VALUES('Mario', false, 4);

--Dados
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(4, 4, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(4, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(4, 3, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(4, 8, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(4, 10, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(4, 10, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(4, 4, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(4, 6, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(4, 11, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(4, 15, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(4, 15, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(4, 12, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(4, 22, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(4, 23, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(4, 25, true);

--Jugador
INSERT INTO JUGADOR (NOMBREJUGADOR, ESHUMANO, ID_JEFEDETERRENO)
	VALUES('Luigi', false, 5);

--Dados
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(5, 1, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(5, 1, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(5, 3, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(5, 4, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(5, 9, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(5, 5, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(5, 9, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(5, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(5, 11, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(5, 12, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(5, 12, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(5, 13, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(5, 22, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(5, 23, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(5, 25, true);

--Jugador
INSERT INTO JUGADOR (NOMBREJUGADOR, ESHUMANO, ID_JEFEDETERRENO)
	VALUES('Bowser', false, 6);

--Dados
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(6, 1, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(6, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(6, 1, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(6, 4, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(6, 10, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(6, 7, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(6, 7, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(6, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(6, 12, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(6, 14, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(6, 15, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(6, 13, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(6, 19, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(6, 20, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(6, 28, true);

--Jugador
INSERT INTO JUGADOR (NOMBREJUGADOR, ESHUMANO, ID_JEFEDETERRENO)
	VALUES('Rosalina', false, 7);

--Dados
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(7, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(7, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(7, 3, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(7, 7, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(7, 10, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(7, 5, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(7, 7, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(7, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(7, 12, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(7, 16, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(7, 13, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(7, 14, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(7, 22, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(7, 19, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(7, 27, true);

--Jugador
INSERT INTO JUGADOR (NOMBREJUGADOR, ESHUMANO, ID_JEFEDETERRENO)
	VALUES('Toon Link', false, 8);

--Dados
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(8, 3, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(8, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(8, 3, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(8, 5, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(8, 10, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(8, 10, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(8, 8, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(8, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(8, 11, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(8, 15, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(8, 14, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(8, 18, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(8, 19, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(8, 24, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(8, 28, true);

--Jugador
INSERT INTO JUGADOR (NOMBREJUGADOR, ESHUMANO, ID_JEFEDETERRENO)
	VALUES('Vaati', false, 9);

--Dados
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(9, 10, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(9, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(9, 3, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(9, 9, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(9, 10, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(9, 9, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(9, 4, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(9, 8, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(9, 13, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(9, 16, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(9, 15, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(9, 13, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(9, 20, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(9, 21, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(9, 25, true);

--Jugador
INSERT INTO JUGADOR (NOMBREJUGADOR, ESHUMANO, ID_JEFEDETERRENO)
	VALUES('Hilda', false, 10);

--Dados
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(10, 5, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(10, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(10, 3, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(10, 4, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(10, 10, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(10, 7, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(10, 4, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(10, 7, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(10, 18, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(10, 12, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(10, 17, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(10, 13, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(10, 19, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(10, 21, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(10, 26, true);

--Jugador
INSERT INTO JUGADOR (NOMBREJUGADOR, ESHUMANO, ID_JEFEDETERRENO)
	VALUES('Wario', false, 11);

--Dados
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(11, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(11, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(11, 3, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(11, 6, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(11, 10, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(11, 7, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(11, 4, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(11, 3, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(11, 11, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(11, 16, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(11, 18, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(11, 15, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(11, 21, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(11, 24, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(11, 27, true);

--Jugador
INSERT INTO JUGADOR (NOMBREJUGADOR, ESHUMANO, ID_JEFEDETERRENO)
	VALUES('Daisy', false, 12);

--Dados
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(12, 1, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(12, 2, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(12, 3, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(12, 4, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(12, 5, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(12, 5, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(12, 8, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(12, 9, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(12, 12, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(12, 16, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(12, 18, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(12, 14, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(12, 22, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(12, 23, true);
INSERT INTO PUZZLEDEDADOS (ID_JUGADOR, ID_DADO, PARAJUGAR)
	VALUES(12, 28, true);