@startuml
hide footbox
title Funcionalidad 3\nEquipos

actor Jugador as j

participant VistaArmarPartida as visAr
participant ControladorArmarPartida as contAr
participant Jugador as eq

j -> visAr : Seleccionar equipo para\nun jugador
activate visAr

visAr -> contAr : definirEquipo(equipo)
activate contAr

contAr -> eq : definirEuipo(equipo)
activate eq

alt Si cantidad de jugadores es mayor a 2

eq --> contAr : SUCCESS

contAr --> visAr : SUCCESS

visAr --> j : Mensaje equipo asignado\ncorrectamente

else Dos o menos jugadores

eq --> contAr : NO_SUCCESS
deactivate eq

contAr --> visAr : NO_SUCCESS
deactivate contAr

visAr --> j : Mensaje cantidad jugadores\ninferior al requerido

end

@enduml