@startuml
hide footbox
title Invocar una criatura

actor Jugador as j

participant VistaBatalla as visBat
participant ControladorBatalla as contBat
participant VistaDespliegues as visDes
participant ControladorDespliegues as contDes
participant Tablero as d
participant Posicion as pos

activate visBat
activate contBat
contBat -> contDes : invocar(Dado dado)
activate contDes

contDes -> d : getDespliegues()
activate d

d --> contDes : Terreno[] despliegues
deactivate d

contDes -> visDes : new VistaDespliegues(Terreno[] despliegues)
activate visDes

visDes --> contDes
deactivate visDes

contDes -> visDes : mostrar()
deactivate contDes

activate j
j -> visDes : Selecciona un despliegue
activate visDes

visDes -> contDes : returnDespliegue(Terreno despliegue)
activate contDes
deactivate visDes

contDes --> contBat : Terreno despliegue
deactivate contDes

contBat --> visBat
j -> visBat : Elige una posicion
visBat -> contBat : comprobarPosicion(Posicion posicion)
contBat -> pos : disponibilidad()

@enduml
