@startuml
hide footbox
title Login

actor Jugadora as j

participant VistaLogin as visLog
participant ControladorLogin as contLog
participant Humano as log

loop Hasta que ingrese o un máximo de 3 intentos por usuario

activate j
j -> visLog : Ingresa datos
activate visLog

j -> visLog : Ingresar
visLog -> contLog : ingresar(String usuario, String pass)
activate contLog

contLog -> log : existe(String usuario)
activate log

alt Si usuario existe
log --> contLog : Respuesta.USUARIO_EXISTE
contLog -> log : comprobar(String usuario, String pass)
alt Si usuario y contraseña calzan
log --> contLog : Respuesta.INGRESO_EXITOSO
contLog --> visLog : mensaje(Respuesta.INGRESO_EXITOSO)
visLog --> j : Mensaje de bienvenida

else Contraseña incorrecta
log --> contLog : Respuesta.PASS_ERRONEA
contLog --> visLog : mensaje(Respuesta.PASS_ERRONEA)
visLog --> j : Mensaje pass incorrecta

end

else Usuario no existe
log --> contLog : Respuesta.USUARIO_NO_EXISTE
deactivate log

contLog --> visLog : mensaje(Respuesta.USUARIO_NO_EXISTE)
deactivate contLog

visLog --> j : Mensaje usuario no existe
deactivate visLog

end

end
@enduml