@startuml
hide footbox
title Realizar ataque

actor Jugador as j

participant VistaBatalla as visBat
participant ControladorBatalla as contBat
participant Accion as at
participant JefeDeTerreno as jefTer
participant Jugador as jug
participant Criatura as cri
participant Dado as d

activate visBat
activate contBat

contBat -> at : realizarAccion(Criatura criaturaAliada,\nElementoEnCampo objetivoEnemigo)
activate at

alt Si enemigo está al alcance
alt Si en el ataque, muere un jefe de terreno
at --> contBat : Respuesta.JEFE_DERROTADO
contBat -> jefTer : getJugador()
activate jefTer

jefTer --> contBat : Jugador jugador
deactivate jefTer

contBat -> jug : eliminarJugador(Jugador jugador)
activate jug

jug --> contBat
deactivate jug
destroy jug

else Si en el ataque, muere una criatura
at --> contBat : Respuesta.CRIATURA_DERROTADA
contBat -> cri : getDado()
activate cri

cri --> contBat : Dado dado
deactivate cri

contBat -> d : eliminarDado(Dado dado)
activate d

d --> contBat
deactivate d
destroy d

else En cualquier otro caso
at --> contBat : Respuesta.ATAQUE_REALIZADO
deactivate at

end

contBat --> visBat : mensaje(Respuesta.ATAQUE_REALIZADO)
visBat --> j : Mostrar mensaje

else Enemigo no está al alcance
contBat --> visBat : mensaje(Respuesta.FUERA_ALCANCE)
deactivate contBat

visBat --> j : Mostrar mensaje

deactivate visBat

end

@enduml
