@startuml
hide footbox
title Torneo

actor Jugador as j

participant VistaTablero as visTab
participant ControladorTablero as contTab
participant VistaTorneo as visTor
participant ControladorTorneo as contTor
participant Torneo as t

== Luego de finalizar una partida del torneo ==

activate j
j -> visTab : Presiona botón\nfinalizar partida
activate visTab

visTab -> contTab : finalizarPartida()
deactivate visTab
activate contTab

alt Si tipo torneo es Todos contra todos

contTab -> contTor : actualizarPuntajes()
activate contTor

contTor -> t : actualizarPuntajes()
activate t

t --> contTor : SUCCESS
deactivate t

contTor -> t : obtenerPuntajes()
activate t

t --> contTor : puntajes[]
deactivate t

contTor -> visTor : new VistaTorneo(puntajes[])
activate visTor

visTor --> contTor : SUCCESS
deactivate visTor

contTor -> visTor : mostrar()
activate visTor

visTor --> j : Mostrar puntajes del torneo
j -> visTor : Presiona botón Siguiente partida
deactivate j

visTor -> contTor : siguientePartida()
deactivate visTor

[<- contTor : Siguiente partida
deactivate contTor

else Si tipo torneo es Sobreviviente
contTab -> contTor : restaurarVida(jugador)
activate contTor

contTor -> t : restaurarVida(jugador)
activate t

t --> contTor : SUCCESS
deactivate t

[<- contTor : Siguiente partida
end
@enduml