@startuml
hide footbox
title Ver información de criatura

actor Jugador as j

participant ControladorBatalla as contBat
participant VistaInfoCriatura as visIn
participant ControladorInfoCriatura as contIn
participant Criatura as cri

contBat -> contIn : verInfoCriatura(Criatura criatura)
activate contIn

contIn -> cri : getInfo()
activate cri

cri --> contIn : String[] infoCriatura
deactivate cri

contIn -> visIn : new VistaInfoCriatura(String[] infoCriatura)
activate visIn

visIn --> contIn
deactivate visIn

contIn -> visIn : mostrar()
activate visIn

visIn --> j : Mostrar información
deactivate visIn

contIn --> contBat
deactivate contIn

@enduml
