@startuml
hide footbox
title Vista de todas las criaturas

actor Jugador as j

participant VistaCriaturas as visCri
participant ControladorCriaturas as contCri
participant ControladorInfoCriatura as cri


activate j
j -> visCri : Clic en el botón de alguna criatura
activate visCri

visCri -> contCri : verInfoCriatura(Criatura criatura)
activate contCri

contCri -> cri : verInfoCriatura(Criatura criatura)
activate cri

== Se muestra la información de la criatura ==

cri --> contCri
deactivate cri

contCri -> visCri
deactivate contCri

visCri --> j
deactivate visCri

@enduml
